<?php
// Static content for the guided-menu WhatsApp bot (whatsapp-bot-router.php):
// welcome copy, the industry/service menu tree, and per-service detail text.
// Sent as free-form text/interactive messages within Meta's 24h
// customer-service window, so none of this needs Meta template approval —
// edit directly, same convention as the WA_BOT_REPLY_* constants in
// config.sample.php. Gallery/video/FAQ content is deliberately omitted (no
// asset pipeline exists for it yet) rather than stubbed with empty keys.

const WA_BOT_WELCOME_BODY =
    "👋 Welcome to CoatCraft Solutions.\n\n" .
    "We provide premium industrial flooring solutions across India:\n" .
    "✔ Industrial Epoxy Flooring\n" .
    "✔ PU Flooring\n" .
    "✔ PU Concrete\n" .
    "✔ ESD Flooring\n" .
    "✔ Chemical Resistant Flooring\n" .
    "✔ Decorative Flooring\n" .
    "✔ Waterproofing\n" .
    "✔ Floor Repairs\n\n" .
    "How can I help you today?";

const WA_BOT_WELCOME_LIST_BUTTON = 'Choose an option';

// 13 industries. category/recommended_services drive Stage 2's blurb + the
// "Explore by Service" jump-in from an industry's Learn More button.
const WA_INDUSTRIES = [
    'automobile' => [
        'label' => 'Automobile',
        'blurb' => 'Automobile plants and service centers need floors that handle heavy vehicle movement, oil spills, and chemical exposure without cracking or staining.',
        'recommended_services' => ['industrial_epoxy', 'pu_flooring'],
    ],
    'warehouse' => [
        'label' => 'Warehouse',
        'blurb' => 'Warehouses need durable, forklift-resistant flooring that withstands constant heavy-load movement and racking point loads.',
        'recommended_services' => ['industrial_epoxy', 'pu_concrete'],
    ],
    'food_industry' => [
        'label' => 'Food Industry',
        'blurb' => 'Food processing floors need hygienic, seamless, steam-cleaning-resistant surfaces that meet food-grade standards.',
        'recommended_services' => ['pu_flooring', 'chemical_resistant_flooring'],
    ],
    'pharma' => [
        'label' => 'Pharma',
        'blurb' => 'Pharma facilities need ESD-safe, chemical-resistant, easy-to-sanitize flooring that meets cleanroom standards.',
        'recommended_services' => ['esd_flooring', 'pu_flooring'],
    ],
    'hospital' => [
        'label' => 'Hospital',
        'blurb' => 'Hospitals need seamless, easy-to-disinfect, anti-microbial flooring for wards, OTs, and corridors.',
        'recommended_services' => ['pu_flooring', 'densi_polished_concrete'],
    ],
    'chemical_plant' => [
        'label' => 'Chemical Plant',
        'blurb' => 'Chemical plants need flooring that resists acids, alkalis, solvents, and heavy chemical spillage.',
        'recommended_services' => ['chemical_resistant_flooring', 'pu_concrete'],
    ],
    'electronics' => [
        'label' => 'Electronics',
        'blurb' => 'Electronics manufacturing needs static-dissipative (ESD) flooring to protect sensitive components.',
        'recommended_services' => ['esd_flooring', 'industrial_epoxy'],
    ],
    'commercial' => [
        'label' => 'Commercial',
        'blurb' => 'Commercial spaces need decorative, durable flooring that balances aesthetics with everyday wear.',
        'recommended_services' => ['metallic_epoxy', 'italian_marble_finish'],
    ],
    'residential' => [
        'label' => 'Residential',
        'blurb' => 'Residential flooring focuses on decorative finishes — metallic, 3D, and marble-effect epoxy — for homes.',
        'recommended_services' => ['metallic_epoxy', 'epoxy_3d'],
    ],
    'parking' => [
        'label' => 'Parking',
        'blurb' => 'Car parks need abrasion- and oil-resistant flooring that handles constant tyre movement and line marking.',
        'recommended_services' => ['car_parking_flooring', 'industrial_epoxy'],
    ],
    'manufacturing' => [
        'label' => 'Manufacturing',
        'blurb' => 'Manufacturing floors need heavy-duty, impact- and chemical-resistant systems for machinery and material handling.',
        'recommended_services' => ['industrial_epoxy', 'pu_concrete'],
    ],
    'cold_storage' => [
        'label' => 'Cold Storage',
        'blurb' => 'Cold storage floors need systems that handle low temperatures, thermal shock, and moisture without cracking.',
        'recommended_services' => ['pu_concrete', 'pu_flooring'],
    ],
    'data_center' => [
        'label' => 'Data Center',
        'blurb' => 'Data centers need static-dissipative, dust-free, easy-to-clean flooring to protect critical equipment.',
        'recommended_services' => ['esd_flooring', 'industrial_epoxy'],
    ],
];

// 20 services, grouped into 3 categories so Stage 3's list menu can paginate
// (Meta caps interactive list messages at 10 rows total) one category per page.
const WA_SERVICES = [
    'industrial_epoxy' => [
        'label' => 'Industrial Epoxy',
        'category' => 'Epoxy Systems',
        'description' => 'A high-strength, seamless epoxy floor coating built for heavy industrial use.',
        'benefits' => 'Excellent abrasion & impact resistance, chemical resistance, seamless & easy to clean, high compressive strength.',
        'applications' => 'Factories, warehouses, automobile plants, manufacturing units.',
        'thickness' => '2mm to 5mm',
        'expected_life' => '8-10 years with proper maintenance',
        'install_time' => '2-5 days depending on area',
        'maintenance' => 'Routine sweeping/mopping, no harsh acids',
        'warranty' => 'Up to 2 years',
        'industries' => 'Automobile, Warehouse, Manufacturing, Parking, Electronics, Data Center',
    ],
    'metallic_epoxy' => [
        'label' => 'Metallic Epoxy',
        'category' => 'Epoxy Systems',
        'description' => 'A decorative epoxy system with metallic pigments creating a 3D, marble-like flowing effect.',
        'benefits' => 'Unique visual finish, seamless, durable, glossy and easy to clean.',
        'applications' => 'Showrooms, offices, retail spaces, homes.',
        'thickness' => '2mm to 3mm',
        'expected_life' => '8-10 years',
        'install_time' => '3-4 days',
        'maintenance' => 'Routine mopping, avoid abrasive cleaners',
        'warranty' => 'Up to 2 years',
        'industries' => 'Commercial, Residential',
    ],
    'pu_flooring' => [
        'label' => 'PU Flooring',
        'category' => 'Specialty Flooring',
        'description' => 'A polyurethane-based floor system offering flexibility, hygiene, and chemical/thermal resistance.',
        'benefits' => 'Steam-cleanable, food-grade options, resists thermal shock, less brittle than epoxy.',
        'applications' => 'Food industry, pharma, hospitals, kitchens, cold storage.',
        'thickness' => '3mm to 6mm',
        'expected_life' => '10-12 years',
        'install_time' => '3-6 days',
        'maintenance' => 'Steam cleaning safe, routine washdown',
        'warranty' => 'Up to 2 years',
        'industries' => 'Food Industry, Pharma, Hospital, Cold Storage',
    ],
    'pu_concrete' => [
        'label' => 'PU Concrete',
        'category' => 'Specialty Flooring',
        'description' => 'A heavy-duty polyurethane concrete system for the toughest thermal and mechanical stress conditions.',
        'benefits' => 'Handles thermal shock and heavy impact, resists grease and organic acids.',
        'applications' => 'Cold storage, heavy manufacturing, warehouses with forklift traffic.',
        'thickness' => '6mm to 9mm',
        'expected_life' => '12-15 years',
        'install_time' => '4-7 days',
        'maintenance' => 'Routine washdown, chemical spill cleanup',
        'warranty' => 'Up to 2 years',
        'industries' => 'Warehouse, Manufacturing, Cold Storage',
    ],
    'esd_flooring' => [
        'label' => 'ESD Flooring',
        'category' => 'Specialty Flooring',
        'description' => 'Static-dissipative flooring that safely conducts static charge away from sensitive equipment.',
        'benefits' => 'Protects electronics from static discharge, seamless, durable.',
        'applications' => 'Electronics assembly, pharma cleanrooms, data centers.',
        'thickness' => '2mm to 4mm',
        'expected_life' => '8-10 years',
        'install_time' => '3-5 days',
        'maintenance' => 'Routine cleaning, periodic conductivity testing',
        'warranty' => 'Up to 2 years',
        'industries' => 'Electronics, Pharma, Data Center',
    ],
    'densi_polished_concrete' => [
        'label' => 'Densi Polished Concrete',
        'category' => 'Specialty Flooring',
        'description' => 'Densified and mechanically polished concrete for a durable, low-maintenance, glossy floor.',
        'benefits' => 'No coating to wear off, dust-free, high shine, cost-effective for large areas.',
        'applications' => 'Warehouses, showrooms, hospitals, commercial spaces.',
        'thickness' => 'Existing slab (no added thickness)',
        'expected_life' => '15-20 years',
        'install_time' => '2-4 days',
        'maintenance' => 'Routine mopping, occasional re-polish',
        'warranty' => 'Up to 1 year',
        'industries' => 'Hospital, Commercial, Warehouse',
    ],
    'chemical_resistant_flooring' => [
        'label' => 'Chemical Resistant Flooring',
        // Meta's interactive list row titles are capped at 24 characters —
        // the full label above exceeds that, so the menu row uses this
        // shorter version while detail text still uses the full label.
        'short_label' => 'Chemical Resistant',
        'category' => 'Specialty Flooring',
        'description' => 'A specialised epoxy/PU system engineered to resist acids, alkalis, and solvents.',
        'benefits' => 'High chemical resistance, seamless, protects the slab from chemical attack.',
        'applications' => 'Chemical plants, labs, food processing units.',
        'thickness' => '3mm to 6mm',
        'expected_life' => '8-10 years',
        'install_time' => '3-6 days',
        'maintenance' => 'Immediate spill cleanup recommended',
        'warranty' => 'Up to 2 years',
        'industries' => 'Chemical Plant, Food Industry',
    ],
    'roller_coating' => [
        'label' => 'Roller Coating',
        'category' => 'Specialty Flooring',
        'description' => 'A thin-film epoxy/PU coating applied by roller — an economical option for light-duty areas.',
        'benefits' => 'Cost-effective, quick to apply, decent chemical & dust resistance.',
        'applications' => 'Light-traffic warehouses, storage areas, back-of-house spaces.',
        'thickness' => '150-300 microns',
        'expected_life' => '3-5 years',
        'install_time' => '1-2 days',
        'maintenance' => 'Routine sweeping/mopping',
        'warranty' => 'Up to 1 year',
        'industries' => 'Warehouse, Manufacturing',
    ],
    'italian_marble_finish' => [
        'label' => 'Italian Marble Finish',
        'category' => 'Epoxy Systems',
        'description' => 'A decorative epoxy system replicating the look of natural Italian marble.',
        'benefits' => 'Premium aesthetic look, seamless, more durable than natural marble.',
        'applications' => 'Showrooms, hotel lobbies, luxury residences.',
        'thickness' => '2mm to 3mm',
        'expected_life' => '8-10 years',
        'install_time' => '3-4 days',
        'maintenance' => 'Routine mopping, avoid abrasive cleaners',
        'warranty' => 'Up to 2 years',
        'industries' => 'Commercial, Residential',
    ],
    'epoxy_3d' => [
        'label' => '3D Epoxy',
        'category' => 'Epoxy Systems',
        'description' => 'A printed or hand-crafted 3D visual embedded under a clear epoxy topcoat.',
        'benefits' => 'Striking visual impact, fully customisable design, durable clear topcoat.',
        'applications' => 'Homes, showrooms, hospitality spaces, feature areas.',
        'thickness' => '2mm to 3mm',
        'expected_life' => '8-10 years',
        'install_time' => '3-5 days',
        'maintenance' => 'Routine mopping, avoid abrasive cleaners',
        'warranty' => 'Up to 2 years',
        'industries' => 'Residential, Commercial',
    ],
    'digital_paper_epoxy' => [
        'label' => 'Digital Paper Epoxy',
        'category' => 'Epoxy Systems',
        'description' => 'A high-resolution printed design layer sealed under a clear epoxy coat.',
        'benefits' => 'Any custom design/branding, durable clear topcoat, seamless finish.',
        'applications' => 'Retail, offices, branded commercial spaces.',
        'thickness' => '2mm to 3mm',
        'expected_life' => '8-10 years',
        'install_time' => '3-5 days',
        'maintenance' => 'Routine mopping, avoid abrasive cleaners',
        'warranty' => 'Up to 2 years',
        'industries' => 'Commercial, Residential',
    ],
    'flakes_epoxy' => [
        'label' => 'Flakes Epoxy',
        'category' => 'Epoxy Systems',
        'description' => 'A textured epoxy system with decorative colour flakes broadcast into the coating.',
        'benefits' => 'Slip resistance, hides minor surface imperfections, decorative texture.',
        'applications' => 'Garages, locker rooms, commercial washrooms.',
        'thickness' => '2mm to 4mm',
        'expected_life' => '6-8 years',
        'install_time' => '2-4 days',
        'maintenance' => 'Routine mopping',
        'warranty' => 'Up to 1 year',
        'industries' => 'Commercial, Residential',
    ],
    'granule_epoxy' => [
        'label' => 'Granule Epoxy',
        'category' => 'Epoxy Systems',
        'description' => 'A durable epoxy system broadcast with quartz/granule aggregate for high slip resistance.',
        'benefits' => 'High slip resistance, hard-wearing, good for wet or high-traffic areas.',
        'applications' => 'Ramps, walkways, wet processing areas.',
        'thickness' => '3mm to 5mm',
        'expected_life' => '8-10 years',
        'install_time' => '2-4 days',
        'maintenance' => 'Routine mopping',
        'warranty' => 'Up to 1 year',
        'industries' => 'Manufacturing, Commercial',
    ],
    'car_parking_flooring' => [
        'label' => 'Car Parking Flooring',
        'category' => 'Finishing & Repair',
        'description' => 'An epoxy/PU system engineered for tyre abrasion, oil resistance, and line marking.',
        'benefits' => 'Abrasion resistant, oil/chemical resistant, supports clear line marking.',
        'applications' => 'Multi-level car parks, showroom parking, residential parking.',
        'thickness' => '2mm to 4mm',
        'expected_life' => '8-10 years',
        'install_time' => '2-4 days',
        'maintenance' => 'Routine sweeping, occasional re-marking',
        'warranty' => 'Up to 2 years',
        'industries' => 'Parking, Commercial, Automobile',
    ],
    'epoxy_waterproofing' => [
        'label' => 'Epoxy Waterproofing',
        'category' => 'Finishing & Repair',
        'description' => 'A seamless epoxy/PU membrane system that waterproofs floors, terraces, and wet areas.',
        'benefits' => 'Fully seamless (no joints to leak), chemical resistant, durable.',
        'applications' => 'Terraces, water tanks, wet processing floors, basements.',
        'thickness' => '2mm to 4mm',
        'expected_life' => '8-10 years',
        'install_time' => '2-4 days',
        'maintenance' => 'Routine cleaning, avoid sharp impact',
        'warranty' => 'Up to 2 years',
        'industries' => 'Commercial, Residential, Manufacturing',
    ],
    'floor_repair' => [
        'label' => 'Floor Repair',
        'category' => 'Finishing & Repair',
        'description' => 'Repair of cracks, dusting, spalling, and undulation in existing concrete or coated floors.',
        'benefits' => 'Restores an existing floor rather than a full replacement, cost-effective.',
        'applications' => 'Any floor showing cracks, dusting, oil staining, or old coating failure.',
        'thickness' => 'Varies by damage (grinding/patching/self-levelling as needed)',
        'expected_life' => 'Depends on the repair method used',
        'install_time' => '1-3 days depending on damage',
        'maintenance' => 'Depends on final coating applied after repair',
        'warranty' => 'Up to 1 year on repaired area',
        'industries' => 'All industries',
    ],
    'epoxy_grouting' => [
        'label' => 'Epoxy Grouting',
        'category' => 'Finishing & Repair',
        'description' => 'Chemical-resistant epoxy grout for tile joints in industrial and food-grade areas.',
        'benefits' => 'Chemical & stain resistant, hygienic, doesn\'t crack like cement grout.',
        'applications' => 'Tiled kitchens, food processing floors, labs.',
        'thickness' => 'Joint-width dependent',
        'expected_life' => '10+ years',
        'install_time' => '1-2 days',
        'maintenance' => 'Routine cleaning',
        'warranty' => 'Up to 1 year',
        'industries' => 'Food Industry, Pharma',
    ],
    'wall_coating' => [
        'label' => 'Wall Coating',
        'category' => 'Finishing & Repair',
        'description' => 'An epoxy/PU wall coating matching the floor system for hygienic, washable walls.',
        'benefits' => 'Washable, chemical resistant, matches the floor system.',
        'applications' => 'Food processing walls, pharma cleanrooms, wash bays.',
        'thickness' => '300 microns to 2mm',
        'expected_life' => '6-8 years',
        'install_time' => '1-3 days',
        'maintenance' => 'Routine washdown',
        'warranty' => 'Up to 1 year',
        'industries' => 'Food Industry, Pharma, Automobile',
    ],
    'coving' => [
        'label' => 'Coving',
        'category' => 'Finishing & Repair',
        'description' => 'A curved cove profile at the floor-wall junction that eliminates hard-to-clean corners.',
        'benefits' => 'No dirt/bacteria trap at corners, easier to clean and sanitize.',
        'applications' => 'Food industry, pharma, hospitals — anywhere hygiene is critical.',
        'thickness' => '50mm to 100mm radius (typical)',
        'expected_life' => 'Matches the floor system it\'s paired with',
        'install_time' => 'Done alongside main flooring installation',
        'maintenance' => 'Routine cleaning',
        'warranty' => 'Matches the paired floor system',
        'industries' => 'Food Industry, Pharma, Hospital',
    ],
    'table_tops' => [
        'label' => 'Table Tops',
        'category' => 'Finishing & Repair',
        'description' => 'Seamless epoxy table top and countertop finishes, decorative or functional.',
        'benefits' => 'Seamless, stain resistant, customisable colour/design.',
        'applications' => 'Offices, cafes, labs, kitchens, retail counters.',
        'thickness' => '2mm to 5mm',
        'expected_life' => '6-8 years',
        'install_time' => '1-2 days',
        'maintenance' => 'Routine wiping, avoid abrasive scrubbing',
        'warranty' => 'Up to 1 year',
        'industries' => 'Commercial, Food Industry',
    ],
];
